<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="4" ignored="4" total="11" passed="0" failed="3" skipped="0">
  <reporter-output>
    <line>
      <![CDATA[Validate app welcome page text...]]>
    </line>
    <line>
      <![CDATA[<h4>Completed the score onboarding flow</h4>]]>
    </line>
    <line>
      <![CDATA[1.Find and select team]]>
    </line>
    <line>
      <![CDATA[2.Verify that the expected page opens correctly.]]>
    </line>
    <line>
      <![CDATA[Validate app welcome page text...]]>
    </line>
    <line>
      <![CDATA[<h4>Completed the score onboarding flow</h4>]]>
    </line>
    <line>
      <![CDATA[1.Find and select team]]>
    </line>
    <line>
      <![CDATA[2.Verify that the expected page opens correctly.]]>
    </line>
    <line>
      <![CDATA[Validate app welcome page text...]]>
    </line>
    <line>
      <![CDATA[<h4>Completed the score onboarding flow</h4>]]>
    </line>
    <line>
      <![CDATA[1.Find and select team]]>
    </line>
    <line>
      <![CDATA[2.Verify that the expected page opens correctly.]]>
    </line>
    <line>
      <![CDATA[Validate app welcome page text...]]>
    </line>
    <line>
      <![CDATA[<h4>Completed the score onboarding flow</h4>]]>
    </line>
    <line>
      <![CDATA[1.Find and select team]]>
    </line>
    <line>
      <![CDATA[2.Verify that the expected page opens correctly.]]>
    </line>
    <line>
      <![CDATA[Validate app welcome page text...]]>
    </line>
    <line>
      <![CDATA[<h4>Completed the score onboarding flow</h4>]]>
    </line>
    <line>
      <![CDATA[1.Find and select team]]>
    </line>
    <line>
      <![CDATA[2.Verify that the expected page opens correctly.]]>
    </line>
    <line>
      <![CDATA[Validate app welcome page text...]]>
    </line>
    <line>
      <![CDATA[<h4>Completed the score onboarding flow</h4>]]>
    </line>
    <line>
      <![CDATA[1.Find and select team]]>
    </line>
    <line>
      <![CDATA[2.Verify that the expected page opens correctly.]]>
    </line>
  </reporter-output>
  <suite started-at="2024-02-15T18:35:40 EST" name="Suite" finished-at="2024-02-15T18:40:13 EST" duration-ms="272823">
    <groups>
    </groups>
    <test started-at="2024-02-15T18:35:40 EST" name="The Score - End to end Framework Test" finished-at="2024-02-15T18:40:13 EST" duration-ms="272823">
      <class name="org.thescore.TheScoreTest.MainTest">
        <test-method is-config="true" signature="ConfigureAppium()[pri:0, instance:org.thescore.TheScoreTest.MainTest@10289886]" started-at="2024-02-15T18:35:40 EST" name="ConfigureAppium" finished-at="2024-02-15T18:36:01 EST" duration-ms="21287" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ConfigureAppium -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:org.thescore.TheScoreTest.MainTest@10289886]" started-at="2024-02-15T18:36:02 EST" name="setUp" finished-at="2024-02-15T18:36:02 EST" duration-ms="607" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method retried="true" signature="TC01_OnboardUserandFindTeam(java.util.HashMap)[pri:0, instance:org.thescore.TheScoreTest.MainTest@10289886]" started-at="2024-02-15T18:36:02 EST" name="TC01_OnboardUserandFindTeam" data-provider="getData" finished-at="2024-02-15T18:36:44 EST" duration-ms="41827" status="SKIP">
          <params>
            <param index="0">
              <value>
                <![CDATA[{sport=Germany Soccer, league=GERMANY, team=Bayern Munich}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Team name is incorrect expected [null] but found [Bayern Munich]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Team name is incorrect expected [null] but found [Bayern Munich]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.thescore.TheScoreTest.MainTest.TC01_OnboardUserandFindTeam(MainTest.java:65)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Validate app welcome page text...]]>
            </line>
            <line>
              <![CDATA[<h4>Completed the score onboarding flow</h4>]]>
            </line>
            <line>
              <![CDATA[1.Find and select team]]>
            </line>
            <line>
              <![CDATA[2.Verify that the expected page opens correctly.]]>
            </line>
          </reporter-output>
        </test-method> <!-- TC01_OnboardUserandFindTeam -->
        <test-method is-config="true" signature="clearAppData()[pri:0, instance:org.thescore.TheScoreTest.MainTest@10289886]" started-at="2024-02-15T18:36:44 EST" name="clearAppData" finished-at="2024-02-15T18:36:45 EST" duration-ms="529" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- clearAppData -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:org.thescore.TheScoreTest.MainTest@10289886]" started-at="2024-02-15T18:36:45 EST" name="setUp" finished-at="2024-02-15T18:36:45 EST" duration-ms="493" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method retried="true" signature="TC01_OnboardUserandFindTeam(java.util.HashMap)[pri:0, instance:org.thescore.TheScoreTest.MainTest@10289886]" started-at="2024-02-15T18:36:45 EST" name="TC01_OnboardUserandFindTeam" data-provider="getData" finished-at="2024-02-15T18:37:30 EST" duration-ms="44627" status="SKIP">
          <params>
            <param index="0">
              <value>
                <![CDATA[{sport=Germany Soccer, league=GERMANY, team=Bayern Munich}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Team name is incorrect expected [null] but found [Bayern Munich]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Team name is incorrect expected [null] but found [Bayern Munich]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.thescore.TheScoreTest.MainTest.TC01_OnboardUserandFindTeam(MainTest.java:65)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:248)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Validate app welcome page text...]]>
            </line>
            <line>
              <![CDATA[<h4>Completed the score onboarding flow</h4>]]>
            </line>
            <line>
              <![CDATA[1.Find and select team]]>
            </line>
            <line>
              <![CDATA[2.Verify that the expected page opens correctly.]]>
            </line>
          </reporter-output>
        </test-method> <!-- TC01_OnboardUserandFindTeam -->
        <test-method is-config="true" signature="clearAppData()[pri:0, instance:org.thescore.TheScoreTest.MainTest@10289886]" started-at="2024-02-15T18:37:30 EST" name="clearAppData" finished-at="2024-02-15T18:37:30 EST" duration-ms="439" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- clearAppData -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:org.thescore.TheScoreTest.MainTest@10289886]" started-at="2024-02-15T18:37:30 EST" name="setUp" finished-at="2024-02-15T18:37:31 EST" duration-ms="462" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="TC01_OnboardUserandFindTeam(java.util.HashMap)[pri:0, instance:org.thescore.TheScoreTest.MainTest@10289886]" started-at="2024-02-15T18:37:31 EST" name="TC01_OnboardUserandFindTeam" data-provider="getData" finished-at="2024-02-15T18:38:11 EST" duration-ms="39848" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[{sport=Germany Soccer, league=GERMANY, team=Bayern Munich}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Team name is incorrect expected [null] but found [Bayern Munich]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Team name is incorrect expected [null] but found [Bayern Munich]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.thescore.TheScoreTest.MainTest.TC01_OnboardUserandFindTeam(MainTest.java:65)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:248)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Validate app welcome page text...]]>
            </line>
            <line>
              <![CDATA[<h4>Completed the score onboarding flow</h4>]]>
            </line>
            <line>
              <![CDATA[1.Find and select team]]>
            </line>
            <line>
              <![CDATA[2.Verify that the expected page opens correctly.]]>
            </line>
          </reporter-output>
        </test-method> <!-- TC01_OnboardUserandFindTeam -->
        <test-method is-config="true" signature="clearAppData()[pri:0, instance:org.thescore.TheScoreTest.MainTest@10289886]" started-at="2024-02-15T18:38:11 EST" name="clearAppData" finished-at="2024-02-15T18:38:12 EST" duration-ms="479" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- clearAppData -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:org.thescore.TheScoreTest.MainTest@10289886]" started-at="2024-02-15T18:38:12 EST" name="setUp" finished-at="2024-02-15T18:38:12 EST" duration-ms="424" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method retried="true" signature="TC01_OnboardUserandFindTeam(java.util.HashMap)[pri:0, instance:org.thescore.TheScoreTest.MainTest@10289886]" started-at="2024-02-15T18:38:12 EST" name="TC01_OnboardUserandFindTeam" data-provider="getData" finished-at="2024-02-15T18:38:40 EST" duration-ms="28243" status="SKIP">
          <params>
            <param index="0">
              <value>
                <![CDATA[{sport=NBA Basketball, league=NBA, team=Toronto Raptors}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Team name is incorrect expected [null] but found [Toronto Raptors]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Team name is incorrect expected [null] but found [Toronto Raptors]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.thescore.TheScoreTest.MainTest.TC01_OnboardUserandFindTeam(MainTest.java:65)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Validate app welcome page text...]]>
            </line>
            <line>
              <![CDATA[<h4>Completed the score onboarding flow</h4>]]>
            </line>
            <line>
              <![CDATA[1.Find and select team]]>
            </line>
            <line>
              <![CDATA[2.Verify that the expected page opens correctly.]]>
            </line>
          </reporter-output>
        </test-method> <!-- TC01_OnboardUserandFindTeam -->
        <test-method is-config="true" signature="clearAppData()[pri:0, instance:org.thescore.TheScoreTest.MainTest@10289886]" started-at="2024-02-15T18:38:40 EST" name="clearAppData" finished-at="2024-02-15T18:38:41 EST" duration-ms="449" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- clearAppData -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:org.thescore.TheScoreTest.MainTest@10289886]" started-at="2024-02-15T18:38:41 EST" name="setUp" finished-at="2024-02-15T18:38:41 EST" duration-ms="449" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method retried="true" signature="TC01_OnboardUserandFindTeam(java.util.HashMap)[pri:0, instance:org.thescore.TheScoreTest.MainTest@10289886]" started-at="2024-02-15T18:38:41 EST" name="TC01_OnboardUserandFindTeam" data-provider="getData" finished-at="2024-02-15T18:39:15 EST" duration-ms="33566" status="SKIP">
          <params>
            <param index="0">
              <value>
                <![CDATA[{sport=NBA Basketball, league=NBA, team=Toronto Raptors}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Team name is incorrect expected [null] but found [Toronto Raptors]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Team name is incorrect expected [null] but found [Toronto Raptors]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.thescore.TheScoreTest.MainTest.TC01_OnboardUserandFindTeam(MainTest.java:65)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:248)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Validate app welcome page text...]]>
            </line>
            <line>
              <![CDATA[<h4>Completed the score onboarding flow</h4>]]>
            </line>
            <line>
              <![CDATA[1.Find and select team]]>
            </line>
            <line>
              <![CDATA[2.Verify that the expected page opens correctly.]]>
            </line>
          </reporter-output>
        </test-method> <!-- TC01_OnboardUserandFindTeam -->
        <test-method is-config="true" signature="clearAppData()[pri:0, instance:org.thescore.TheScoreTest.MainTest@10289886]" started-at="2024-02-15T18:39:15 EST" name="clearAppData" finished-at="2024-02-15T18:39:15 EST" duration-ms="428" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- clearAppData -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:org.thescore.TheScoreTest.MainTest@10289886]" started-at="2024-02-15T18:39:15 EST" name="setUp" finished-at="2024-02-15T18:39:16 EST" duration-ms="476" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="TC01_OnboardUserandFindTeam(java.util.HashMap)[pri:0, instance:org.thescore.TheScoreTest.MainTest@10289886]" started-at="2024-02-15T18:39:16 EST" name="TC01_OnboardUserandFindTeam" data-provider="getData" finished-at="2024-02-15T18:39:47 EST" duration-ms="31759" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[{sport=NBA Basketball, league=NBA, team=Toronto Raptors}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Team name is incorrect expected [null] but found [Toronto Raptors]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Team name is incorrect expected [null] but found [Toronto Raptors]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.thescore.TheScoreTest.MainTest.TC01_OnboardUserandFindTeam(MainTest.java:65)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:248)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Validate app welcome page text...]]>
            </line>
            <line>
              <![CDATA[<h4>Completed the score onboarding flow</h4>]]>
            </line>
            <line>
              <![CDATA[1.Find and select team]]>
            </line>
            <line>
              <![CDATA[2.Verify that the expected page opens correctly.]]>
            </line>
          </reporter-output>
        </test-method> <!-- TC01_OnboardUserandFindTeam -->
        <test-method is-config="true" signature="clearAppData()[pri:0, instance:org.thescore.TheScoreTest.MainTest@10289886]" started-at="2024-02-15T18:39:48 EST" name="clearAppData" finished-at="2024-02-15T18:39:49 EST" duration-ms="507" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- clearAppData -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:org.thescore.TheScoreTest.MainTest@10289886]" started-at="2024-02-15T18:39:49 EST" name="setUp" finished-at="2024-02-15T18:39:49 EST" duration-ms="539" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="TC02_RefreshResultsBug()[pri:0, instance:org.thescore.TheScoreTest.MainTest@10289886]" started-at="2024-02-15T18:39:49 EST" name="TC02_RefreshResultsBug" description="Test to demonstrate a bug in the app related to refreshing results" finished-at="2024-02-15T18:40:11 EST" duration-ms="21933" status="FAIL">
          <exception class="org.openqa.selenium.TimeoutException">
            <message>
              <![CDATA[Expected condition failed: waiting for invisibility of Located by By.chained({AppiumBy.id: com.fivemobile.thescore:id/error_view}) (tried for 2 second(s) with 500 milliseconds interval)
Build info: version: '4.17.0', revision: 'e52b1be057*'
System info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '21.0.1'
Driver info: io.appium.java_client.android.AndroidDriver
Capabilities {appium:app: C:\Users\bungh\eclipse-work..., appium:appPackage: com.fivemobile.thescore, appium:autoGrantPermissions: true, appium:automationName: UIAutomator2, appium:databaseEnabled: false, appium:desired: {app: C:\Users\bungh\eclipse-work..., autoGrantPermissions: true, automationName: UIAutomator2, deviceName: AshDevice, platformName: ANDROID}, appium:deviceApiLevel: 33, appium:deviceManufacturer: Google, appium:deviceModel: sdk_gphone_x86_64, appium:deviceName: emulator-5554, appium:deviceScreenDensity: 420, appium:deviceScreenSize: 1080x2400, appium:deviceUDID: emulator-5554, appium:javascriptEnabled: true, appium:locationContextEnabled: false, appium:networkConnectionEnabled: true, appium:pixelRatio: 2.625, appium:platformVersion: 13, appium:statBarHeight: 128, appium:takesScreenshot: true, appium:viewportRect: {height: 2081, left: 0, top: 128, width: 1080}, appium:warnings: {}, appium:webStorageEnabled: false, platformName: ANDROID}
Session ID: bd1d51eb-0e9a-443a-a971-a0e34b55098a]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.openqa.selenium.TimeoutException: Expected condition failed: waiting for invisibility of Located by By.chained({AppiumBy.id: com.fivemobile.thescore:id/error_view}) (tried for 2 second(s) with 500 milliseconds interval)
Build info: version: '4.17.0', revision: 'e52b1be057*'
System info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '21.0.1'
Driver info: io.appium.java_client.android.AndroidDriver
Capabilities {appium:app: C:\Users\bungh\eclipse-work..., appium:appPackage: com.fivemobile.thescore, appium:autoGrantPermissions: true, appium:automationName: UIAutomator2, appium:databaseEnabled: false, appium:desired: {app: C:\Users\bungh\eclipse-work..., autoGrantPermissions: true, automationName: UIAutomator2, deviceName: AshDevice, platformName: ANDROID}, appium:deviceApiLevel: 33, appium:deviceManufacturer: Google, appium:deviceModel: sdk_gphone_x86_64, appium:deviceName: emulator-5554, appium:deviceScreenDensity: 420, appium:deviceScreenSize: 1080x2400, appium:deviceUDID: emulator-5554, appium:javascriptEnabled: true, appium:locationContextEnabled: false, appium:networkConnectionEnabled: true, appium:pixelRatio: 2.625, appium:platformVersion: 13, appium:statBarHeight: 128, appium:takesScreenshot: true, appium:viewportRect: {height: 2081, left: 0, top: 128, width: 1080}, appium:warnings: {}, appium:webStorageEnabled: false, platformName: ANDROID}
Session ID: bd1d51eb-0e9a-443a-a971-a0e34b55098a
at org.openqa.selenium.support.ui.WebDriverWait.timeoutException(WebDriverWait.java:84)
at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:228)
at org.thescore.pageObjects.android.ChooseTeamPage.searchAndhandleError(ChooseTeamPage.java:109)
at org.thescore.TheScoreTest.MainTest.TC02_RefreshResultsBug(MainTest.java:95)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.openqa.selenium.TimeoutException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC02_RefreshResultsBug -->
        <test-method is-config="true" signature="clearAppData()[pri:0, instance:org.thescore.TheScoreTest.MainTest@10289886]" started-at="2024-02-15T18:40:11 EST" name="clearAppData" finished-at="2024-02-15T18:40:12 EST" duration-ms="541" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- clearAppData -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:org.thescore.TheScoreTest.MainTest@10289886]" started-at="2024-02-15T18:40:12 EST" name="tearDown" finished-at="2024-02-15T18:40:13 EST" duration-ms="991" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="tearDownSuite()[pri:0, instance:org.thescore.TheScoreTest.MainTest@10289886]" started-at="2024-02-15T18:40:13 EST" name="tearDownSuite" finished-at="2024-02-15T18:40:13 EST" duration-ms="11" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownSuite -->
      </class> <!-- org.thescore.TheScoreTest.MainTest -->
    </test> <!-- The Score - End to end Framework Test -->
  </suite> <!-- Suite -->
</testng-results>
