<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-ENVP6HG" failures="2" tests="7" name="org.thescore.TheScoreTest.MainTest" time="248.625" errors="1" timestamp="2024-02-15T18:40:13 EST" skipped="4">
  <testcase classname="org.thescore.TheScoreTest.MainTest" name="TC01_OnboardUserandFindTeam" time="32.622">
    <failure message="Team name is incorrect expected [null] but found [Toronto Raptors]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Team name is incorrect expected [null] but found [Toronto Raptors]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.thescore.TheScoreTest.MainTest.TC01_OnboardUserandFindTeam(MainTest.java:65)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:248)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
    <system-out>
      <![CDATA[Validate app welcome page text...
<h4>Completed the score onboarding flow</h4>
1.Find and select team
2.Verify that the expected page opens correctly.]]>
    </system-out>
  </testcase> <!-- TC01_OnboardUserandFindTeam -->
  <testcase classname="org.thescore.TheScoreTest.MainTest" name="TC01_OnboardUserandFindTeam" time="42.769">
    <skipped/>
    <system-out>
      <![CDATA[Validate app welcome page text...
<h4>Completed the score onboarding flow</h4>
1.Find and select team
2.Verify that the expected page opens correctly.]]>
    </system-out>
  </testcase> <!-- TC01_OnboardUserandFindTeam -->
  <testcase classname="org.thescore.TheScoreTest.MainTest" name="TC01_OnboardUserandFindTeam" time="45.517">
    <skipped/>
    <system-out>
      <![CDATA[Validate app welcome page text...
<h4>Completed the score onboarding flow</h4>
1.Find and select team
2.Verify that the expected page opens correctly.]]>
    </system-out>
  </testcase> <!-- TC01_OnboardUserandFindTeam -->
  <testcase classname="org.thescore.TheScoreTest.MainTest" name="TC01_OnboardUserandFindTeam" time="40.803">
    <failure message="Team name is incorrect expected [null] but found [Bayern Munich]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Team name is incorrect expected [null] but found [Bayern Munich]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.thescore.TheScoreTest.MainTest.TC01_OnboardUserandFindTeam(MainTest.java:65)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:248)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
    <system-out>
      <![CDATA[Validate app welcome page text...
<h4>Completed the score onboarding flow</h4>
1.Find and select team
2.Verify that the expected page opens correctly.]]>
    </system-out>
  </testcase> <!-- TC01_OnboardUserandFindTeam -->
  <testcase classname="org.thescore.TheScoreTest.MainTest" name="TC01_OnboardUserandFindTeam" time="29.311">
    <skipped/>
    <system-out>
      <![CDATA[Validate app welcome page text...
<h4>Completed the score onboarding flow</h4>
1.Find and select team
2.Verify that the expected page opens correctly.]]>
    </system-out>
  </testcase> <!-- TC01_OnboardUserandFindTeam -->
  <testcase classname="org.thescore.TheScoreTest.MainTest" name="TC01_OnboardUserandFindTeam" time="34.522">
    <skipped/>
    <system-out>
      <![CDATA[Validate app welcome page text...
<h4>Completed the score onboarding flow</h4>
1.Find and select team
2.Verify that the expected page opens correctly.]]>
    </system-out>
  </testcase> <!-- TC01_OnboardUserandFindTeam -->
  <testcase classname="org.thescore.TheScoreTest.MainTest" name="TC02_RefreshResultsBug" time="23.081">
    <error message="Expected condition failed: waiting for invisibility of Located by By.chained({AppiumBy.id: com.fivemobile.thescore:id/error_view}) (tried for 2 second(s) with 500 milliseconds interval)
Build info: version: &#039;4.17.0&#039;, revision: &#039;e52b1be057*&#039;
System info: os.name: &#039;Windows 11&#039;, os.arch: &#039;amd64&#039;, os.version: &#039;10.0&#039;, java.version: &#039;21.0.1&#039;
Driver info: io.appium.java_client.android.AndroidDriver
Capabilities {appium:app: C:\Users\bungh\eclipse-work..., appium:appPackage: com.fivemobile.thescore, appium:autoGrantPermissions: true, appium:automationName: UIAutomator2, appium:databaseEnabled: false, appium:desired: {app: C:\Users\bungh\eclipse-work..., autoGrantPermissions: true, automationName: UIAutomator2, deviceName: AshDevice, platformName: ANDROID}, appium:deviceApiLevel: 33, appium:deviceManufacturer: Google, appium:deviceModel: sdk_gphone_x86_64, appium:deviceName: emulator-5554, appium:deviceScreenDensity: 420, appium:deviceScreenSize: 1080x2400, appium:deviceUDID: emulator-5554, appium:javascriptEnabled: true, appium:locationContextEnabled: false, appium:networkConnectionEnabled: true, appium:pixelRatio: 2.625, appium:platformVersion: 13, appium:statBarHeight: 128, appium:takesScreenshot: true, appium:viewportRect: {height: 2081, left: 0, top: 128, width: 1080}, appium:warnings: {}, appium:webStorageEnabled: false, platformName: ANDROID}
Session ID: bd1d51eb-0e9a-443a-a971-a0e34b55098a" type="org.openqa.selenium.TimeoutException">
      <![CDATA[org.openqa.selenium.TimeoutException: Expected condition failed: waiting for invisibility of Located by By.chained({AppiumBy.id: com.fivemobile.thescore:id/error_view}) (tried for 2 second(s) with 500 milliseconds interval)
Build info: version: '4.17.0', revision: 'e52b1be057*'
System info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '21.0.1'
Driver info: io.appium.java_client.android.AndroidDriver
Capabilities {appium:app: C:\Users\bungh\eclipse-work..., appium:appPackage: com.fivemobile.thescore, appium:autoGrantPermissions: true, appium:automationName: UIAutomator2, appium:databaseEnabled: false, appium:desired: {app: C:\Users\bungh\eclipse-work..., autoGrantPermissions: true, automationName: UIAutomator2, deviceName: AshDevice, platformName: ANDROID}, appium:deviceApiLevel: 33, appium:deviceManufacturer: Google, appium:deviceModel: sdk_gphone_x86_64, appium:deviceName: emulator-5554, appium:deviceScreenDensity: 420, appium:deviceScreenSize: 1080x2400, appium:deviceUDID: emulator-5554, appium:javascriptEnabled: true, appium:locationContextEnabled: false, appium:networkConnectionEnabled: true, appium:pixelRatio: 2.625, appium:platformVersion: 13, appium:statBarHeight: 128, appium:takesScreenshot: true, appium:viewportRect: {height: 2081, left: 0, top: 128, width: 1080}, appium:warnings: {}, appium:webStorageEnabled: false, platformName: ANDROID}
Session ID: bd1d51eb-0e9a-443a-a971-a0e34b55098a
at org.openqa.selenium.support.ui.WebDriverWait.timeoutException(WebDriverWait.java:84)
at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:228)
at org.thescore.pageObjects.android.ChooseTeamPage.searchAndhandleError(ChooseTeamPage.java:109)
at org.thescore.TheScoreTest.MainTest.TC02_RefreshResultsBug(MainTest.java:95)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- TC02_RefreshResultsBug -->
  <system-out>
    <![CDATA[Validate app welcome page text...
<h4>Completed the score onboarding flow</h4>
1.Find and select team
2.Verify that the expected page opens correctly.
Validate app welcome page text...
<h4>Completed the score onboarding flow</h4>
1.Find and select team
2.Verify that the expected page opens correctly.
Validate app welcome page text...
<h4>Completed the score onboarding flow</h4>
1.Find and select team
2.Verify that the expected page opens correctly.
Validate app welcome page text...
<h4>Completed the score onboarding flow</h4>
1.Find and select team
2.Verify that the expected page opens correctly.
Validate app welcome page text...
<h4>Completed the score onboarding flow</h4>
1.Find and select team
2.Verify that the expected page opens correctly.
Validate app welcome page text...
<h4>Completed the score onboarding flow</h4>
1.Find and select team
2.Verify that the expected page opens correctly.]]>
  </system-out>
</testsuite> <!-- org.thescore.TheScoreTest.MainTest -->
